"""Checks on the Hyprland Lua config in dotconfig/hypr/: every file it
requires exists in the repo, and every file parses."""

import re
import shutil
import subprocess
from pathlib import Path

import pytest

HYPR = Path(__file__).resolve().parent.parent / "dotconfig" / "hypr"
# Written on each machine, not shipped: generated by monitors.sh, or personal.
OPTIONAL = {"monitors_active", "local"}


def test_every_required_file_is_in_the_repo():
    text = (HYPR / "hyprland.lua").read_text()
    required = set(re.findall(r'^\s*(?:pcall\()?require[,( ]+"([\w_]+)"', text, re.M))
    assert {"env", "plugins", "gamemode", "keybindings", "windowrules"} <= required
    for name in required - OPTIONAL:
        assert (HYPR / f"{name}.lua").exists(), name


@pytest.mark.skipif(not shutil.which("luac"), reason="needs luac (lua)")
@pytest.mark.parametrize("path", sorted(HYPR.glob("*.lua")), ids=lambda p: p.name)
def test_the_lua_parses(path):
    result = subprocess.run(["luac", "-p", str(path)], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
