animations {
    enabled = true

    # --- CURVAS BEZIER (El secreto del flow) ---
    # Una curva que se pasa un poco del final y regresa (overshoot)
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    # Curva suave pero rápida estilo Material Design 3
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    # Curva para que las ventanas "vuelen"
    bezier = fluent_404, 0, 1, 0, 1

    #Bordes
    bezier = linear, 0, 0, 1, 1

    #hyprfocus
    bezier = focusBounce, 0.2, 0.9, 0, 1.1

    bezier = fluent_move, 0.2, 1, 0.36, 1

    # --- ASIGNACIÓN DE ANIMACIONES ---
    # Ventanas entrando: Pop-in al 80% de tamaño con rebote
    animation = windowsIn, 1, 5, overshot, popin 80%
    # Ventanas saliendo: Se deslizan hacia abajo y desaparecen
    animation = windowsOut, 1, 5, md3_accel, slide
    # Cambio de foco: Transición rápida entre ventanas
    animation = windowsMove, 1, 5, md3_decel

    # El degradado del borde rotando (Esto se ve espectacular)
    animation = border, 1, 10, default
    animation = borderangle, 1, 100, md3_decel, loop

    # Desvanecidos
    animation = fadeIn, 1, 5, md3_decel
    animation = fadeOut, 1, 5, md3_accel
    
    # Workspaces: Deslizamiento horizontal súper fluido
    animation = workspaces, 1, 6, overshot, slide

    # Bordes infinitos
    animation = borderangle, 1, 50, linear, loop

    # Hyprfocus
    animation = hyprfocusIn, 1, 2, focusBounce
    animation = hyprfocusOut, 1, 2, focusBounce

    animation = windowsMove, 1, 9, fluent_move
    animation = windowsIn, 1, 4, fluent_move, slide
    animation = windowsOut, 1, 4, fluent_move, slide
}
