animations {
    enabled = true

    # --- BEZIER CURVES ---
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = fluent_404, 0, 1, 0, 1

    # Borders
    bezier = linear, 0, 0, 1, 1

    # hyprfocus
    bezier = focusBounce, 0.2, 0.9, 0, 1.1

    bezier = fluent_move, 0.2, 1, 0.36, 1

    # --- ANIMATION ASSIGNMENTS ---
    animation = windowsIn, 1, 5, overshot, popin 80%
    animation = windowsOut, 1, 5, md3_accel, slide
    animation = windowsMove, 1, 5, md3_decel

    # Rotating border gradient
    animation = border, 1, 10, default
    animation = borderangle, 1, 100, md3_decel, loop

    # Fades
    animation = fadeIn, 1, 5, md3_decel
    animation = fadeOut, 1, 5, md3_accel

    # Workspaces: smooth horizontal slide
    animation = workspaces, 1, 6, overshot, slide

    # Infinite border loop
    animation = borderangle, 1, 50, linear, loop

    # Hyprfocus
    animation = hyprfocusIn, 1, 2, focusBounce
    animation = hyprfocusOut, 1, 2, focusBounce

    animation = windowsMove, 1, 9, fluent_move
    animation = windowsIn, 1, 4, fluent_move, slide
    animation = windowsOut, 1, 4, fluent_move, slide
}
