# Swipe 3 dedos hacia ARRIBA -> Abrir Menú de Apps (Rofi/Wofi)
gesture = 3, up, dispatcher, exec, sh -c "pkill -x rofi || rofi -show drun -theme ~/.config/rofi/launchers/type-3/style-1.rasi"

# Movimiento horizontal -> Cambia de Workspace fluidamente
gesture = 3, horizontal, workspace

# Swipe hacia abajo -> Muestra el Espacio Mágico (Scratchpad)
gesture = 3, down, special, magic

# Swipe 4 dedos hacia ARRIBA -> Pantalla Completa
gesture = 4, up, fullscreen

# Swipe 4 dedos hacia ABAJO -> Hacer Master (Swap with master)
gesture = 4, down, dispatcher, exec, hyprctl dispatch layoutmsg swapwithmaster master

# Pellizco hacia AFUERA (Pinch-Out) -> Cerrar la ventana actual
gesture = 4, pinchout, close

# --- 🔍 ZOOM CON GESTOS (Estilo macOS) ---
gesture = 2, pinchin, dispatcher, exec, sh -c 'Z=$(hyprctl getoption cursor:zoom_factor | awk "/float:/ {print \$2}"); hyprctl keyword cursor:zoom_factor $(awk "BEGIN {print $Z + 0.5}")'
gesture = 2, pinchout, dispatcher, exec, sh -c 'Z=$(hyprctl getoption cursor:zoom_factor | awk "/float:/ {print \$2}"); hyprctl keyword cursor:zoom_factor $(awk "BEGIN {v=$Z - 0.5; print (v<1)?1:v}")'




