-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


-----------------
---- COLORS  ----
-----------------

require("colors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Layout is generated by `monitors.sh` (setup/apply) into monitors_active.lua.
-- Run `monitors.sh setup` to configure orientation / order / primary per monitor.
local mon_ok = pcall(require, "monitors_active")
if not mon_ok then
    -- Catch-all fallback if the generated file is missing or broken.
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1.0 })
end

-- React to monitor hotplug: regenerate the layout + reload via monitors.sh.
-- (`apply` is idempotent and only reloads if the generated output changed,
--  which prevents an event -> reload -> event loop.)
for _, ev in ipairs({ "monitor.added", "monitor.removed" }) do
    pcall(function()
        hl.on(ev, function() hl.dispatch(hl.dsp.exec_cmd("monitors.sh apply")) end)
    end)
end


-- Entering a mode says which one and how to leave. Global: keybindings.lua uses
-- it. Not an hl.on hook, since keybinds.submap never fires on 0.56.2.
SUBMAP_MODES = {
    groupmode  = { icon = "preferences-desktop", key = "Super + G",         hint = "Group mode" },
    screenshot = { icon = "camera-photo",        key = "Super + Shift + S", hint = "Screenshot mode" },
    winctl     = { icon = "view-fullscreen",     key = "Super + R",         hint = "Window control mode" },
}

function toggle_submap(name)
    local mode = SUBMAP_MODES[name]
    if hl.get_current_submap() == name then
        hl.dispatch(hl.dsp.submap("reset"))
        return
    end
    hl.dispatch(hl.dsp.submap(name))
    if mode then
        hl.exec_cmd('notify-send -u low -i "' .. mode.icon .. '" "' .. mode.hint .. '" "Press ' .. mode.key .. ' again or Esc to exit"')
        -- swaync ignores -t
        hl.exec_cmd("sleep 1.5; swaync-client --close-latest")
    end
end


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use. Global on purpose: keybindings.lua and gestures.lua
-- are require()d further down and read them from here, the same way colors.lua
-- hands its palette to this file. Change a program once, here.
terminal    = "kitty"
fileManager = "kitty --class yazi-kitty -e yazi"
menu        = "rofi -show drun -modes 'drun,window,ssh,run' -theme ~/.config/rofi/hyprflow/launcher-centered.rasi"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function ()
    -- A shutdown in game mode (power cut, Steam's power menu) leaves its state
    -- behind; a fresh session always starts on the normal desktop. No-op when
    -- game mode is off.
    hl.exec_cmd("game-mode.sh off")
    -- Detects monitors, generates the layout + Waybar config, and starts Waybar.
    hl.exec_cmd("monitors.sh apply")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("~/.local/lib/hyprflow/activate-linux.py")
    hl.exec_cmd("rgb-sync.sh --last")
    -- The headset gets the LED colour again whenever it turns on.
    hl.exec_cmd("~/.local/lib/hyprflow/headset-watch.py")
    hl.exec_cmd("nm-applet --indicator")
    -- Bluetooth agent: shows the pairing and authorization prompts of any device
    -- (passkeys, confirmations, controllers asking to connect). Without one BlueZ
    -- cancels those requests. Also adds a tray icon.
    hl.exec_cmd("blueman-applet")
    -- Hold PS + Options on a controller to toggle game mode (Hyprland itself
    -- does not read gamepads).
    hl.exec_cmd("~/.local/lib/hyprflow/pad-listener.py")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

require("env")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {active_border_main, active_border_fade, active_border_fade, active_border_main}, angle = 45 },
            inactive_border = inactive_border,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "master",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 0.80,

        -- Floating windows only (tiled ones drop it in windowrules.lua): wide,
        -- and cast downwards so they read as lifted.
        shadow = {
            enabled      = true,
            range        = 40,
            render_power = 3,
            offset       = {0, 8},
            color        = 0x77000000,
        },

        -- Scratchpad (Super+Z): blur what's behind it instead of dimming it.
        dim_special = 0.0,

        blur = {
            enabled   = true,
            size      = 6,
            passes    = 2,
            vibrancy  = 0.1696,
            special   = true,
        },
    },

    animations = {
        enabled = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
require("animations")

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- Group / tab colors
hl.config({
    group = {
        col = {
            border_active          = group_border_active,
            border_inactive        = inactive_border,
            border_locked_active   = group_border_active,
            border_locked_inactive = inactive_border,
        },
        groupbar = {
            col = {
                active   = group_bar_active,
                inactive = group_bar_inactive,
            },
            text_color = group_text,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
        mfact     = 0.75
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
        middle_click_paste      = false, -- Disable pasting the primary selection with the middle mouse button
    },
})

hl.config({
    cursor = {
        inactive_timeout = 10,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "es,us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll         = true,
            disable_while_typing   = true,
            clickfinger_behavior   = true,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "logitech-mx-master-3s",
    sensitivity = 0.3,
})

hl.device({
    name          = "apple-inc.-magic-trackpad",
    sensitivity   = -0.3,
    accel_profile = "adaptive",
    natural_scroll = true,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
require("keybindings")


---------------------
---- GESTURES ----
---------------------

require("gestures")


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
require("windowrules")


-----------------
---- PLUGINS ----
-----------------

-- After windowrules: hyprglass reads the tags those rules set.
require("plugins")


-------------------
---- GAME MODE ----
-------------------

require("gamemode")


---------------
---- LOCAL ----
---------------

-- Per machine extras, outside the repo: ~/.config/hypr/local.lua is loaded if
-- it exists (mounting a games drive, a device only this machine has, ...).
-- install.sh never writes it.
pcall(require, "local")
