-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


-----------------
---- COLORS  ----
-----------------

require("colors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Layout is generated by `monitors.sh` (setup/apply) into monitors_active.lua.
-- Run `monitors.sh setup` to configure orientation / order / primary per monitor.
local mon_ok = pcall(require, "monitors_active")
if not mon_ok then
    -- Catch-all fallback if the generated file is missing or broken.
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1.0 })
end

-- React to monitor hotplug: regenerate the layout + reload via monitors.sh.
-- Guarded by a global so config reloads don't stack duplicate handlers.
-- (`apply` is idempotent and only reloads if the generated output changed,
--  which prevents an event -> reload -> event loop.)
if not _G.__hyprflow_monitor_hooks then
    _G.__hyprflow_monitor_hooks = true
    for _, ev in ipairs({ "monitor.added", "monitor.removed" }) do
        pcall(function()
            hl.on(ev, function() hl.dispatch(hl.dsp.exec_cmd("monitors.sh apply")) end)
        end)
    end
end


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "kitty --class yazi-kitty -e yazi"
local menu        = "rofi -show drun -modes 'drun,window,run' -theme ~/.config/rofi/hyprflow/launcher-centered.rasi"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Detects monitors, generates the layout + Waybar config, and starts Waybar.
    hl.exec_cmd("monitors.sh apply")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("eww open activate-linux")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE",                      "24")
hl.env("HYPRCURSOR_SIZE",                   "24")
hl.env("XCURSOR_THEME",                     "Bibata-Modern-Classic")
hl.env("XDG_CURRENT_DESKTOP",               "Hyprland")
hl.env("XDG_SESSION_TYPE",                  "wayland")
hl.env("XDG_SESSION_DESKTOP",               "Hyprland")
hl.env("MOZ_ENABLE_WAYLAND",                "1")

hl.env("QT_QPA_PLATFORM",                   "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR",       "0")
hl.env("QT_QPA_PLATFORMTHEME",              "qt6ct")
hl.env("QT_QPA_PLATFORMTHEME_Qt5",          "qt5ct")
hl.env("GTK_THEME",                         "Adwaita-dark")
hl.env("GTK_ICON_THEME",                    "Adwaita")
hl.env("GTK_APPLICATION_PREFER_DARK_THEME", "1")

-- Nvidia
hl.env("LIBVA_DRIVER_NAME",                 "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME",         "nvidia")
hl.env("ELECTRON_OZONE_PLATFORM_HINT",      "auto")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {active_border_main, active_border_fade, active_border_fade, active_border_main}, angle = 45 },
            inactive_border = inactive_border,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "master",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 0.80,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
require("animations")

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- Group / tab colors
hl.config({
    group = {
        col = {
            border_active          = group_border_active,
            border_inactive        = inactive_border,
            border_locked_active   = group_border_active,
            border_locked_inactive = inactive_border,
        },
        groupbar = {
            col = {
                active   = group_bar_active,
                inactive = group_bar_inactive,
            },
            text_color = group_text,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
        mfact     = 0.75
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


-----------------
---- PLUGINS ----
-----------------

hl.config({
    plugin = {
        hyprfocus = {
            keyboard_focus_animation = "slide",
            mouse_focus_animation    = "slide",
            fade_opacity             = 0.99,
            slide_height             = 8,
            only_on_monitor_change   = true,
        },

        hymission = {
            outer_padding_top    = 92,
            outer_padding_right  = 32,
            outer_padding_bottom = 32,
            outer_padding_left   = 32,
            row_spacing          = 32,
            column_spacing       = 32,
            min_window_length    = 120,
            min_preview_short_edge = 32,
            small_window_boost   = 1.35,
            max_preview_scale    = 0.95,
            workspace_overview_max_preview_scale = 0.95,
            min_slot_scale       = 0.10,
            natural_scale_flex   = 0.22,
            layout_engine        = "grid",
            layout_scale_weight  = 1.0,
            layout_space_weight  = 0.10,

            expand_selected_window             = 1,
            overview_focus_follows_mouse       = 1,
            multi_workspace_sort_recent_first  = 1,
            niri_mode                          = 0,
            niri_scroll_pixels_per_delta       = 1.0,
            niri_workspace_scale               = 1.0,
            toggle_switch_mode                 = 0,
            switch_toggle_auto_next            = 1,
            switch_release_key                 = "Super_L",
            gesture_invert_vertical            = 0,
            one_workspace_per_row              = 0,
            only_active_workspace              = 0,
            only_active_monitor                = 0,
            show_special                       = 0,
            workspace_change_keeps_overview    = 1,

            workspace_strip_anchor             = "left",
            workspace_strip_empty_mode         = "existing",
            workspace_strip_thickness          = 160,
            workspace_strip_gap                = 24,
            hide_bar_when_strip                = 1,
            hide_bar_animation                 = 1,
            hide_bar_animation_blur            = 1,
            hide_bar_animation_move_multiplier = 0.8,
            hide_bar_animation_scale_divisor   = 1.1,
            hide_bar_animation_alpha_end       = 0,
            bar_single_mission_control         = 0,
            show_focus_indicator               = 0,

            debug_logs                         = 0,
            debug_surface_logs                 = 0,
        },
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "es,us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll         = true,
            disable_while_typing   = true,
            clickfinger_behavior   = true,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "logitech-mx-master-3s",
    sensitivity = 0.3,
})

hl.device({
    name          = "apple-inc.-magic-trackpad",
    sensitivity   = -0.3,
    accel_profile = "adaptive",
    natural_scroll = true,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
require("keybindings")


---------------------
---- GESTURES ----
---------------------

require("gestures")


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
require("windowrules")