-- Auto-generated by monitors.sh — do not edit manually
-- This file is overwritten on every Hyprland startup.
-- Initial values are the last detected ports.
AOC      = "HDMI-A-1"
ASUS     = "DP-1"
NZXT     = "DP-2"
THINKPAD = "eDP-1"
