-- monitors_active.lua — DEFAULT layout (catch-all).
--
-- This is the fallback shipped in the repo. The real, per-machine layout is
-- GENERATED by `monitors.sh` (setup/apply) into ~/.config/hypr/monitors_active.lua,
-- which overwrites this file at runtime. On a fresh install this catch-all keeps
-- every monitor working (preferred mode, auto-positioned) until `monitors.sh apply`
-- regenerates the layout from the saved profile.

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1.0 })
