# This file contains the identifiers for the monitors connected to the system. 
# Maybe this ID can change in some cases, but the script bin/monitors.sh will update it automatically. 
# Its not recommended to change it manually, but if you want to do it, just replace the value with the correct one for each monitor,
# but remember that the names must be exactly the same as the ones shown in the output of `hyprctl monitors` command.
$AOC = HDMI-A-1
$ASUS = DP-1
$NZXT = DP-2
$THINKPAD = eDP-1
