################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Monitor layout left to right:
# $AOC (vertical) -> $NZXT -> $ASUS (vertical) -> $THINKPAD

source = ~/.config/hypr/monitors_ids.conf

monitor=$AOC, 1920x1080@60.0, 0x0, 1.0, transform, 1
monitor=$NZXT, 2560x1440@120.0, 1080x0, 1.0
monitor=$ASUS, 1920x1080@60.0, 3640x0, 1.0, transform, 3
monitor=$THINKPAD, 1920x1080@60.0, 4720x0, 1.0

workspace = 1, monitor:$NZXT
workspace = 2, monitor:$NZXT

workspace = 3, monitor:$AOC, layoutopt:orientation:top
workspace = 6, monitor:$AOC, layoutopt:orientation:top

workspace = 4, monitor:$ASUS, layoutopt:orientation:top
workspace = 8, monitor:$ASUS, layoutopt:orientation:top

workspace = 5, monitor:$THINKPAD
workspace = 7, monitor:$THINKPAD
