windowrule {
    name = smart-borders-tiled
    match:float = 0
    match:workspace = w[tv1]
    border_size = 0
    rounding = 0
}


windowrule {
    name = smart-borders-fullscreen
    match:float = 0
    match:workspace = f[1]
    border_size = 0
    rounding = 0
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = global-suppress-maximize
    match:class = .*
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = no-focus-xwayland-tooltips
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
    no_focus = on
}

# Only affects floating/secondary windows from VS Code
windowrule {
    name = center-vscode-dialogs
    match:class = ^(Code|code-url-handler)$
    match:fullscreen = 0
    center = on
}

# Only affects floating windows from Rofi
windowrule {
    name = center-rofi
    match:class = ^(Rofi|rofi)$
    match:fullscreen = 0
    center = on
}

windowrule {
    name = background-terminal
    match:class = kitty-bg
    monitor = DVI-I-1
    float = on
    pin = on
    
    # PERFORMANCE
    no_focus = on
    no_initial_focus = on
    border_size = 0
    #noshadow = on
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = waypaper-minimal
    match:class = ^(waypaper)$
    float = on
    size = 800 540
    center = on
    opacity = 0.92 override 0.92 override
}


windowrule {
    name = spotify-mini
    match:class = ^(Spotify)$
    float = on
    size = 900 600
    center = on
}


windowrule {
    name = xdg-file-picker
    match:class = ^(xdg-desktop-portal-gtk)$
    float = on
    size = 1200 800
    center = on
}


windowrule {
    name = audio-sink-switcher
    match:class = ^(kitty-sinkswitch)$
    float = on
    size = 450 150
    center = on
    pin = on
    animation = slide
}

windowrule {
    name = cal-popup
    match:class = ^(cal-popup)$
    float = on
    size = 200 200
    center = on
    pin = on
    animation = slide
}

windowrule {
    name = theme-picker
    match:class = ^(kitty-theme-picker)$
    float = on
    size = 420 260
    center = on
    pin = on
    animation = popin
    opacity = 0.7 override 0.7 override
}

windowrule {
    name = kitty-transparent
    match:class = ^(kitty)$
    opacity = 0.7 override 0.7 override
}

windowrule {
    name = btop-float
    match:class = ^(btop-float)$
    float = on
    size = 900 600
    center = on
    pin = on
    opacity = 0.85 override 0.85 override
}

windowrule {
    name = updates-float
    match:class = ^(updates-float)$
    float = on
    size = 900 600
    center = on
    pin = on
    opacity = 0.85 override 0.85 override
}

windowrule {
    name = satty-float
    match:class = ^(com\.gabm\.satty)$
    float = on
    center = on
}