$background = rgb(1A1B26)
$foreground = rgb(F1F1F1)
$color0 = rgb(222330)
$color1 = rgb(F7768E)
$color2 = rgb(7AA2F7)
$color3 = rgb(E0AF68)
$color4 = rgb(BB9AF7)

$active_border_main = rgba(FFFFFFcc)
$active_border_fade = rgba(FFFFFF10)
$inactive_border = rgba(595959aa)

$group_border_active = rgba(7C3AEDee)
$group_bar_active = rgba(7C3AEDff)
$group_bar_inactive = rgba(2D2D2D66)
$group_text = rgba(FFFFFFff)

