shell /bin/zsh
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size        11.5


symbol_map U+2500-U+257F,U+2580-U+259F JetBrainsMono Nerd Font Mono
