#!/usr/bin/env bash
#
# Writes hyprlock-geometry.conf and hyprlock-extras.conf, read by hyprlock.conf.
#
# --wait-backdrop waits for the frosted background to be rebuilt. The lock path
# omits it and takes the plain wallpaper for one lock rather than stall.
#
# Coordinates are offsets from the edge named by halign/valign: y counts up from
# the bottom, negative x counts in from the right.
set -euo pipefail

wait_for_backdrop=false
[ "${1:-}" = "--wait-backdrop" ] && wait_for_backdrop=true

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/hyprflow"
GEOMETRY_FILE="$CONFIG_DIR/hypr/hyprlock-geometry.conf"
EXTRAS_FILE="$CONFIG_DIR/hypr/hyprlock-extras.conf"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

REFERENCE_WIDTH=2560
REFERENCE_HEIGHT=1440

GENERATED_HEADER="# Generated by geometry.sh -- do not edit by hand."

die() { printf 'geometry.sh: %s\n' "$1" >&2; exit 1; }

run_or_empty() {
    "$@" 2>/dev/null || true
}

emit_section() {
    local title="$1" pair name width=0
    shift

    for pair in "$@"; do
        name=${pair%%=*}
        [ "${#name}" -gt "$width" ] && width=${#name}
    done

    [ -n "$title" ] && printf '# %s\n' "$title"
    for pair in "$@"; do
        printf '$%-*s = %s\n' "$width" "${pair%%=*}" "${pair#*=}"
    done
    printf '\n'
}

command -v hyprctl >/dev/null 2>&1 || die "hyprctl not found; is Hyprland running?"
command -v jq >/dev/null 2>&1 || die "jq not found"

# Queried once: two calls can disagree if a display is plugged in between.
monitors_json=$(hyprctl monitors -j 2>/dev/null) || die "could not query monitors"
workspace_one_monitor=$(hyprctl workspaces -j 2>/dev/null \
    | jq -r 'map(select(.id == 1)) | first | .monitor // ""') || workspace_one_monitor=""

primary_line=$(printf '%s' "$monitors_json" | jq -r \
    --arg forced "${HYPRLOCK_MONITOR:-}" \
    --arg workspace_one "$workspace_one_monitor" '
    [ .[]
      | . as $monitor
      # transform 1/3/5/7 means rotated 90/270, swapping width and height
      | ($monitor.transform % 2 == 1) as $rotated
      | {
          name: $monitor.name,
          width:  (( if $rotated then $monitor.height else $monitor.width  end ) / $monitor.scale | round),
          height: (( if $rotated then $monitor.width  else $monitor.height end ) / $monitor.scale | round),
          is_forced:      ($monitor.name == $forced),
          has_workspace_1: ($monitor.name == $workspace_one)
        }
    ]
    | (map(select(.is_forced)) | first)
      // (map(select(.has_workspace_1)) | first)
      // (sort_by(.width) | last)
    | "\(.name) \(.width) \(.height)"
')

# Captured first, not piped into read: read returns non-zero on empty input and
# set -e would abort before writing anything.
[ -n "$primary_line" ] || die "no monitor found"
read -r monitor_name screen_width screen_height <<<"$primary_line"
all_monitors=$(printf '%s' "$monitors_json" | jq -r '.[].name')

scale=$(awk -v w="$screen_width" -v h="$screen_height" \
            -v rw="$REFERENCE_WIDTH" -v rh="$REFERENCE_HEIGHT" \
    'BEGIN { x = w / rw; y = h / rh; print (x < y ? x : y) }')

scaled() { awk -v value="$1" -v scale="$scale" 'BEGIN { printf "%d", value * scale + 0.5 }'; }
centred() { echo $(( $1 + ($2 - $3) / 2 )); }
# centred_text <origin> <container> <ink-h> <descent>
# Text is placed by its box but centres on its ink; the descent bridges them.
centred_text() { echo $(( $1 + ($2 - $3) / 2 - $4 )); }

avatar_file="$CONFIG_DIR/hypr/avatar.png"
[ -x "$SCRIPT_DIR/avatar.sh" ] && "$SCRIPT_DIR/avatar.sh" || true

resolve_wallpaper() {
    local path
    path=$(run_or_empty awww query | sed -n 's/.*image: //p' | head -1)
    if [ -z "$path" ]; then
        path=$(sed -n 's/^wallpaper *= *//p' \
            "$CONFIG_DIR/waypaper/config.ini" 2>/dev/null | head -1)
    fi
    printf '%s' "${path/#\~/$HOME}"
}

resolve_backdrop() {
    local args=("$wallpaper" "$screen_width" "$screen_height" "$band_height")
    [ -x "$SCRIPT_DIR/backdrop.sh" ] || { printf '%s' "$wallpaper"; return; }
    [ "$wait_for_backdrop" = true ] && args=(--blocking "${args[@]}")
    "$SCRIPT_DIR/backdrop.sh" "${args[@]}" 2>/dev/null || printf '%s' "$wallpaper"
}

resolve_cover_art() {
    local path fallback="$CACHE_DIR/lockart-none.png"
    [ -x "$SCRIPT_DIR/music.sh" ] || { printf '%s' "$fallback"; return; }
    path=$("$SCRIPT_DIR/music.sh" --art-now 2>/dev/null) || path=""
    printf '%s' "${path:-$fallback}"
}

wallpaper=$(resolve_wallpaper)
band_height=$(scaled 560)
backdrop=$(resolve_backdrop)
lockart=$(resolve_cover_art)

# A label is placed by its box, but the eye judges the ink: at the clock's size
# the box reserves ~87px below the digits and ~18px to their left.
#
#   bearing  ink inset from the box's left edge
#   descent  gap between the ink's bottom and the box's bottom
#   ink_h    the ink's real height
#
# Fractions of the font size, so they survive rescaling. Measured with Pango
# against JetBrainsMono Nerd Font, stable from 15px to 300px; another font
# needs re-measuring.
BEARING_BOLD=0.08
BEARING_REGULAR=0.10
DESCENT_RATIO=0.40

metric() { awk -v size="$1" -v ratio="$2" 'BEGIN { printf "%d", size * ratio + 0.5 }'; }

clock_font=$(scaled 300)
date_font=$(scaled 26)
user_font=$(scaled 22)
hud_font=$(scaled 20)

clock_bearing=$(metric "$clock_font" "$BEARING_BOLD")
clock_descent=$(metric "$clock_font" "$DESCENT_RATIO")
clock_ink_h=$clock_font
date_bearing=$(metric "$date_font" "$BEARING_REGULAR")
date_descent=$(metric "$date_font" "$DESCENT_RATIO")
user_descent=$(metric "$user_font" "$DESCENT_RATIO")
user_ink_h=$user_font
hud_descent=$(metric "$hud_font" "$DESCENT_RATIO")
hud_ink_h=$hud_font

bar_margin=$(scaled 128)
bar_x=$bar_margin
bar_y=$(scaled 48)
bar_width=$(( screen_width - 2 * bar_margin ))
bar_height=$(scaled 120)
bar_radius=$(scaled 24)
bar_top=$(( bar_y + bar_height ))
bar_padding=$(scaled 24)

avatar_size=$(scaled 80)
avatar_x=$(( bar_x + bar_padding ))
avatar_y=$(centred "$bar_y" "$bar_height" "$avatar_size")

user_x=$(( avatar_x + avatar_size + bar_padding ))
user_y=$(centred_text "$bar_y" "$bar_height" "$user_ink_h" "$user_descent")

input_width=$(( screen_width - $(scaled 1320) ))
input_height=$(scaled 76)
input_radius=$(scaled 14)
input_x=$(centred "$bar_x" "$bar_width" "$input_width")
input_y=$(centred "$bar_y" "$bar_height" "$input_height")

hud_y=$(centred_text "$bar_y" "$bar_height" "$hud_ink_h" "$hud_descent")
battery_x=$(( -(bar_margin + $(scaled 92)) ))
layout_x=$(( battery_x - $(scaled 340) ))

text_left=$(( bar_x + $(scaled 7) ))
clock_baseline=$(( bar_top + $(scaled 32) ))
clock_x=$(( text_left - clock_bearing ))
clock_y=$(( clock_baseline - clock_descent ))
clock_shadow_size=$(scaled 8)
clock_shadow_passes=2

clock_ink_top=$(( clock_descent + clock_ink_h ))
date_x=$(( text_left - date_bearing ))
date_y=$(( clock_y + clock_ink_top + $(scaled 20) - date_descent ))

art_size=$(scaled 96)
art_radius=$(scaled 10)
art_x=$(( -bar_margin ))
art_y=$(( bar_top + $(scaled 32) ))

music_x=$(( art_x - art_size - $(scaled 28) ))
title_size=$(scaled 24)
subtitle_size=$hud_font
subtitle_y=$(( art_y + $(scaled 12) ))
title_y=$(( subtitle_y + $(scaled 44) ))

{
    printf '%s\n' "$GENERATED_HEADER"
    printf '# Monitor: %s  %sx%s logical  ·  scale: %s\n\n' \
        "$monitor_name" "$screen_width" "$screen_height" "$scale"

    emit_section "" \
        "primary=$monitor_name" \
        "avatar=$avatar_file" \
        "lockart=$lockart"

    emit_section "Clock and date" \
        "clock_size=$clock_font" \
        "clock_shadow_size=$clock_shadow_size" \
        "clock_shadow_passes=$clock_shadow_passes" \
        "clock_x=$clock_x" \
        "clock_y=$clock_y" \
        "date_size=$date_font" \
        "date_x=$date_x" \
        "date_y=$date_y"

    emit_section "Glass bar" \
        "bar_w=$bar_width" \
        "bar_h=$bar_height" \
        "bar_r=$bar_radius" \
        "bar_x=$bar_x" \
        "bar_y=$bar_y"

    emit_section "Avatar and user name" \
        "avatar_size=$avatar_size" \
        "avatar_x=$avatar_x" \
        "avatar_y=$avatar_y" \
        "user_size=$user_font" \
        "user_x=$user_x" \
        "user_y=$user_y"

    emit_section "Password field" \
        "input_w=$input_width" \
        "input_h=$input_height" \
        "input_r=$input_radius" \
        "input_x=$input_x" \
        "input_y=$input_y"

    emit_section "Status indicators" \
        "hud_size=$hud_font" \
        "hud_y=$hud_y" \
        "layout_x=$layout_x" \
        "batt_x=$battery_x"

    emit_section "Now playing" \
        "art_size=$art_size" \
        "art_r=$art_radius" \
        "art_x=$art_x" \
        "art_y=$art_y" \
        "music_x=$music_x" \
        "title_size=$title_size" \
        "title_y=$title_y" \
        "subtitle_size=$subtitle_size" \
        "subtitle_y=$subtitle_y"
} >"$GEOMETRY_FILE"

# Per-monitor: only the primary takes the backdrop with the band baked in. One
# shared image would paint that band onto screens with no clock or bar, and a
# rotated monitor swells it to a third of its height. Secondaries carry no
# content, so they get hyprlock's own blur -- which works on whole backgrounds
# only, and that is exactly why the primary's band has to be a file.
emit_background() {
    cat <<EOF
background {
    monitor = $1
    path = $2
    color = \$bg
    blur_passes = $3
EOF
    shift 3
    while [ "$#" -gt 0 ]; do
        printf '    %s\n' "$1"
        shift
    done
    printf '}\n\n'
}

{
    printf '%s\n\n' "$GENERATED_HEADER"
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        if [ "$name" = "$monitor_name" ]; then
            emit_background "$name" "$backdrop" 0
        else
            emit_background "$name" "$wallpaper" 3 \
                "blur_size = 7" \
                "noise = 0.011" \
                "contrast = 0.9" \
                "brightness = 0.6"
        fi
    done <<<"$all_monitors"
} >"$EXTRAS_FILE"

battery_script="$SCRIPT_DIR/battery.sh"
if [ -x "$battery_script" ] && [ -n "$("$battery_script")" ]; then
    cat >>"$EXTRAS_FILE" <<EOF
label {
    monitor = \$primary
    text = cmd[update:30000] $battery_script
    font_family = \$font
    font_size = \$hud_size
    color = \$fg_dim
    position = \$batt_x, \$hud_y
    halign = right
    valign = bottom
}
EOF
fi
